name: CI | Run launch-times metrics
on:
  workflow_call:

jobs:
  launch-times-tests:
    runs-on: metrics
    steps:
    - name: run launch times on qemu
      run: bash tests/metrics/gha-run.sh run-test-launchtimes-qemu

    - name: run launch times on clh
      run:  bash tests/metrics/gha-run.sh run-test-launchtimes-clh
